CREATE TABLE CustomerDetails (
    CustomerID INT PRIMARY KEY AUTO_INCREMENT,
    FirstName VARCHAR(255) NOT NULL,
    MiddleName VARCHAR(250),
    LastName VARCHAR(255) NOT NULL,
    DateOfBirth DATE NOT NULL,
    Gender VARCHAR(50) NOT NULL,
    Nationality VARCHAR(50) NOT NULL,
    ResidentialAddress TEXT NOT NULL,
    MailingAddress TEXT,
    PhoneNumber VARCHAR(15) NOT NULL,
    EmailAddress VARCHAR(100) NOT NULL,
    Username VARCHAR(100) UNIQUE NOT NULL,
    AccntPassword VARCHAR(100) NOT NULL,
    CardPin INT NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE KYCDetails (
    IDNumber VARCHAR(50) NOT NULL PRIMARY KEY,
    IDType VARCHAR(100) NOT NULL,
    IDIssueDate DATE NOT NULL,
    IDExpiryDate DATE NOT NULL,
    NomineeName VARCHAR(100),
    NomineeRelationship VARCHAR(50),
    CustomerID INT,
    FOREIGN KEY (CustomerID) REFERENCES CustomerDetails(CustomerID)
);

CREATE TABLE AccountDetails (
    AccountType VARCHAR(50) NOT NULL,
    InitialDepositAmount INT UNSIGNED NOT NULL,
    AccountCurrency VARCHAR(10) NOT NULL,
    DebitCard BOOLEAN DEFAULT FALSE,
    CreditCard BOOLEAN DEFAULT FALSE,
    InternetBanking BOOLEAN DEFAULT FALSE,
    MobileBanking BOOLEAN DEFAULT FALSE,
    CustomerID INT,
    FOREIGN KEY (CustomerID) REFERENCES CustomerDetails(CustomerID)
);

CREATE TABLE Transactions (
    TransactionID INT AUTO_INCREMENT PRIMARY KEY,
    TotalAmount INT NOT NULL,
    Deposit INT,
    Withdraw INT,
    TransactionAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CustomerID INT,
    FOREIGN KEY (CustomerID) REFERENCES CustomerDetails(CustomerID)
);

ALTER TABLE CustomerDetails MODIFY COLUMN FirstName VARCHAR(255) DEFAULT NULL;
ALTER TABLE CustomerDetails MODIFY COLUMN MiddleName VARCHAR(250) DEFAULT NULL;
ALTER TABLE CustomerDetails MODIFY COLUMN LastName VARCHAR(255) DEFAULT NULL;
ALTER TABLE CustomerDetails MODIFY COLUMN DateOfBirth DATE DEFAULT NULL;
ALTER TABLE CustomerDetails MODIFY COLUMN Gender VARCHAR(50) DEFAULT NULL;
ALTER TABLE CustomerDetails MODIFY COLUMN Nationality VARCHAR(50) DEFAULT NULL;
ALTER TABLE CustomerDetails MODIFY COLUMN ResidentialAddress TEXT DEFAULT NULL;
ALTER TABLE CustomerDetails MODIFY COLUMN PhoneNumber VARCHAR(15) DEFAULT NULL;
ALTER TABLE CustomerDetails MODIFY COLUMN EmailAddress VARCHAR(200) DEFAULT NULL;
ALTER TABLE CustomerDetails MODIFY COLUMN Username VARCHAR(100) UNIQUE DEFAULT NULL;
ALTER TABLE CustomerDetails MODIFY COLUMN AccntPassword VARCHAR(100) DEFAULT NULL;
ALTER TABLE CustomerDetails MODIFY COLUMN CardPin INT DEFAULT NULL;

ALTER TABLE KYCDetails MODIFY COLUMN IDNumber VARCHAR(50) DEFAULT NULL;
ALTER TABLE KYCDetails MODIFY COLUMN IDType VARCHAR(100) DEFAULT NULL;
ALTER TABLE KYCDetails MODIFY COLUMN IDIssueDate DATE DEFAULT NULL;
ALTER TABLE KYCDetails MODIFY COLUMN IDExpiryDate DATE DEFAULT NULL;

ALTER TABLE Transactions MODIFY COLUMN TotalAmount INT DEFAULT NULL;

ALTER TABLE AccountDetails MODIFY COLUMN AccountType VARCHAR(50) DEFAULT NULL;
ALTER TABLE AccountDetails MODIFY COLUMN InitialDepositAmount INT DEFAULT NULL;
ALTER TABLE AccountDetails MODIFY COLUMN AccountCurrency VARCHAR(200) DEFAULT NULL;
